container:
  image: node:8

build_task:
  node_modules_cache:
    folder: app/node_modules
    fingerprint_script: cat app/package-lock.json
    populate_script: cd app && npm ci
  script: cd app && npm run build
