version: 1.0.{build}
image: Ubuntu1804
init:
- sh: cd app
install:
- sh: npm install
cache: app/node_modules
build_script:
- sh: npm run build
artifacts:
- path: app/index.html
- path: app/dist/*
deploy: off
